### PR TITLE
Change docstring to meet actual usage of plotattr

### PR DESCRIPTION
**Pull request by jjerphan**
**Main changes**:
 - this is a really small fix

**Context**:

If one use:
```julia
help(plot)
```

One is invited to type:

```julia
plotattr([attrib])
plotattr(:Axis) # for instance
```

but this should be:

```julia
plotattr(attrib)
plotattr(:Axis) # for instance 
```

This fixes the doc comment accordingly.

### CODE REVIEW

**Comment by jjerphan** [comment]
cc @daschw

**Comment by daschw** [comment]
Nice, but you should make this pull request against JuliaPlots/Plots.jl instead of your fork, so we can merge it. See http://docs.juliaplots.org/latest/contributing/#development-workflow.

**Comment by daschw** [comment]
Now that I think about it. The notation `f(x[, y])` in docstrings usually means that `y` is an optional agrument for `f`. Since `plotattr()` can also be called without arguments, I think the current version actually makes sense.

**Comment by jjerphan** [comment]
> Now that I think about it. The notation f(x[, y]) in docstrings usually means that y is an optional agrument for f. Since plotattr() can also be called without arguments, I think the current version actually makes sense.

Oh, yes you're right. I'm closing this PR.

**Pull request closed without merging**
